initial_positions:
    joint_1: 0      # base rotation
    joint_2: 0      # lower arm
    joint_3: 0      # top arm
    joint_4: 0      # wrist
    joint_5: 0      # claw base tilt
    joint_6: 0      # right claw
    joint_7: 0      # left claw (mimic joint)